/** Auto-generated by scripts/write-community-config.mjs */
export const communityConfig = {
  supabaseUrl: 'https://ilcevfnevhlsufftnvag.supabase.co',
  supabaseAnonKey: 'sb_publishable_Yzt2oRAzoM8iwBNpbmG1-Q_jJjeVqdg',
} as const;

export function isCommunityEnabled(): boolean {
  return communityConfig.supabaseUrl.trim().length > 0 && communityConfig.supabaseAnonKey.trim().length > 0;
}
