/** Auto-generated by scripts/write-community-config.mjs */
export const communityConfig = {
  supabaseUrl: '',
  supabaseAnonKey: '',
} as const;

export function isCommunityEnabled(): boolean {
  return communityConfig.supabaseUrl.trim().length > 0 && communityConfig.supabaseAnonKey.trim().length > 0;
}
